feat: better error messages around auth (404 handling)
If you hit a 404 we will show this error now:

```
Error: Permission denied or this route does not exist

Your token "{TOKEN_NAME}" has permissions: data:read

You can create a new token at:
https://dashboard.mux.com/settings/access-tokens
Then run 'mux login' to authenticate with the new token.
```

Note this detail:

As far as I can tell all 404s are all basically "Insufficient Privileges"

- /assets/:wrong_id will return 400 for *any* value of :wrong_id

```
❯ ./dist/mux assets get "HoGN5KDgq5hEdA98v33cWolrMCvSCLejgLBqI4yiA7k"
Error: 401 {"error":{"type":"invalid_parameters","messages":["Invalid external asset ID, mismatching environment"]}}
```

If you somehow truly hit a nonexistant route:

- GET /nonexistant-route
- GET /assets/:id (but your token doesn't have permissions)

Both of these return:

```
Error: 404 {"error":{"type":"not_found","messages":["The requested resource either doesn't exist or you don't have access to it."]}}
```

But with the CLI, it would be fairly hard (impossible?) to hit a "true"
404

So for all intents & purposes, we'll presume the 404 is a permission
issue and tell you what permissions the current token has and how you
can create a new one.